//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GifToWOW.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GifToWOW.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Column:(0:Auto): 的本地化字符串。
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column: 的本地化字符串。
        /// </summary>
        internal static string ColumnCount {
            get {
                return ResourceManager.GetString("ColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column width: 的本地化字符串。
        /// </summary>
        internal static string ColumnWidth {
            get {
                return ResourceManager.GetString("ColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert complete 的本地化字符串。
        /// </summary>
        internal static string ConvertEnd {
            get {
                return ResourceManager.GetString("ConvertEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert start 的本地化字符串。
        /// </summary>
        internal static string ConvertStart {
            get {
                return ResourceManager.GetString("ConvertStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output directory not found 的本地化字符串。
        /// </summary>
        internal static string DesDirNotExists {
            get {
                return ResourceManager.GetString("DesDirNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration: 的本地化字符串。
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FrameCount: 的本地化字符串。
        /// </summary>
        internal static string FrameCount {
            get {
                return ResourceManager.GetString("FrameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fps: 的本地化字符串。
        /// </summary>
        internal static string FrameRate {
            get {
                return ResourceManager.GetString("FrameRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gif frame count must greater than 1 的本地化字符串。
        /// </summary>
        internal static string GifMustAnimate {
            get {
                return ResourceManager.GetString("GifMustAnimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gif not found 的本地化字符串。
        /// </summary>
        internal static string GifNotExists {
            get {
                return ResourceManager.GetString("GifNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageSize: 的本地化字符串。
        /// </summary>
        internal static string ImageSize {
            get {
                return ResourceManager.GetString("ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output: 的本地化字符串。
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process complete 的本地化字符串。
        /// </summary>
        internal static string ProcessEnd {
            get {
                return ResourceManager.GetString("ProcessEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process start 的本地化字符串。
        /// </summary>
        internal static string ProcessStart {
            get {
                return ResourceManager.GetString("ProcessStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row count: 的本地化字符串。
        /// </summary>
        internal static string RowCount {
            get {
                return ResourceManager.GetString("RowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row height: 的本地化字符串。
        /// </summary>
        internal static string RowHeight {
            get {
                return ResourceManager.GetString("RowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 s 的本地化字符串。
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select gif 的本地化字符串。
        /// </summary>
        internal static string SelectGif {
            get {
                return ResourceManager.GetString("SelectGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select output directory 的本地化字符串。
        /// </summary>
        internal static string SelectOptDir {
            get {
                return ResourceManager.GetString("SelectOptDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom: 的本地化字符串。
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
